/**
 * Headers Schema Mapping - Derived 1:1 from Backend/Headers.gs
 * Defines canonical column schemas and tables for all HSE modules.
 */
'use strict';

const headersMap = {
    'Users': ['id', 'name', 'email', 'password', 'passwordHash', 'role', 'department', 'employeeCode', 'active', 'photo', 'permissions', 'lastLogin', 'lastLogout', 'lastPresenceAt', 'isOnline', 'activeSessionId', 'loginHistory', 'postLoginPolicySeenAt', 'profilePublicToken', 'profilePublicTokenExpiry', 'mfaEnabled', 'mfaSecretEnc', 'mfaEnrolledAt', 'createdAt', 'updatedAt'],
    'UserVersions': ['id', 'userId', 'userEmail', 'userName', 'userRole', 'userDepartment', 'currentVersion', 'firstSeenVersion', 'previousVersion', 'lastSeenAt', 'firstSeenAt', 'sessionCount', 'reportCount', 'userAgent', 'platform', 'isMobile', 'screenSize', 'language', 'updatedAt'],
    'Incidents': ['id', 'isoCode', 'title', 'description', 'location', 'siteId', 'siteName', 'sublocation', 'sublocationId', 'sublocationName', 'date', 'severity', 'incidentType', 'affiliation', 'department', 'reportedBy', 'employeeCode', 'employeeNumber', 'employeeName', 'employeeJob', 'employeeDepartment', 'status', 'rootCause', 'correctiveAction', 'preventiveAction', 'actionPlan', 'affectedType', 'affectedCode', 'affectedName', 'affectedJobTitle', 'affectedDepartment', 'affectedContact', 'injuryDescription', 'losses', 'actionsTaken', 'contractorName', 'image', 'attachments', 'investigation', 'closureDate', 'actionOwner', 'requiresApproval', 'approvedBy', 'approvedAt', 'rejectedBy', 'rejectedAt', 'rejectionReason', 'createdBy', 'createdAt', 'updatedAt'],
    'IncidentNotifications': ['id', 'notificationNumber', 'date', 'location', 'siteId', 'siteName', 'sublocation', 'sublocationId', 'sublocationName', 'department', 'incidentType', 'affiliation', 'contractorName', 'employeeCode', 'employeeName', 'employeeJob', 'employeeDepartment', 'description', 'injuryDescription', 'losses', 'actions', 'reporterName', 'reporterCode', 'createdBy', 'createdAt', 'updatedAt'],
    'SafetyAlerts': ['id', 'alertNumber', 'sequentialNumber', 'incidentId', 'incidentType', 'incidentDate', 'incidentLocation', 'who', 'description', 'facts', 'causes', 'lessonsLearned', 'preventiveMeasures', 'locationImage', 'causesImage', 'notificationNumber', 'preparedBy', 'approvedBy', 'approvedAt', 'issueDate', 'status', 'createdBy', 'createdAt', 'updatedAt'],
    'Incident_Analysis_Settings': ['id', 'enabledSections', 'updatedAt', 'updatedBy', 'createdAt'],
    'IncidentsRegistry': ['id', 'sequentialNumber', 'incidentId', 'incidentType', 'factory', 'incidentLocation', 'incidentDate', 'incidentDay', 'incidentTime', 'shift', 'employeeAffiliation', 'employeeCode', 'employeeName', 'employeeJob', 'employeeDepartment', 'incidentDetails', 'incidentDetailsBrief', 'injuryDescription', 'injuredPart', 'losses', 'equipmentCause', 'actionsTaken', 'leaveStartDate', 'returnToWorkDate', 'totalLeaveDays', 'treatingDoctor', 'status', 'createdAt', 'updatedAt'],
    'NearMiss': ['id', 'isoCode', 'type', 'severity', 'date', 'observerName', 'phone', 'location', 'siteName', 'subLocation', 'department', 'description', 'potentialConsequences', 'correctiveProposed', 'correctiveDescription', 'attachments', 'status', 'reportedBy', 'isAnonymous', 'gpsLocation', 'gpsMapLink', 'createdAt', 'updatedAt'],
    'PTW': ['id', 'workType', 'workDescription', 'location', 'department', 'startDate', 'endDate', 'responsible', 'status', 'approvals', 'requiredPPE', 'riskAssessment', 'riskNotes', 'approvalCircuitOwnerId', 'approvalCircuitName', 'skipApprovalFlow', 'createdBy', 'createdById', 'updatedBy', 'updatedById', 'createdAt', 'updatedAt'],
    'PTWRegistry': [
        'id', 'sequentialNumber', 'permitId', 'openDate', 'permitType', 'permitTypeDisplay', 'requestingParty', 'locationId', 'location', 'sublocationId', 'sublocation',
        'timeFrom', 'timeTo', 'totalTime', 'authorizedParty', 'workDescription', 'supervisor1', 'supervisor2', 'status',
        'paperPermitNumber', 'equipment', 'tools', 'toolsList', 'teamMembersText',
        'hotWorkDetails', 'hotWorkOther', 'confinedSpaceDetails', 'confinedSpaceOther', 'heightWorkDetails', 'heightWorkOther',
        'electricalWorkType', 'coldWorkType', 'otherWorkType', 'excavationLength', 'excavationWidth', 'excavationDepth', 'soilType',
        'preStartChecklist', 'lotoApplied', 'governmentPermits', 'riskAssessmentAttached', 'gasTesting', 'mocRequest',
        'ppeNotes', 'requiredPPE', 'riskLikelihood', 'riskConsequence', 'riskScore', 'riskLevel', 'riskNotes',
        'manualApprovalsText', 'manualClosureApprovalsText', 'closureDate', 'closureReason', 'isManualEntry',
        'approvalCircuitOwnerId', 'approvalCircuitName', 'skipApprovalFlow', 'createdBy', 'createdById', 'updatedBy', 'updatedById',
        'createdAt', 'updatedAt'
    ],
    'PTWIdMapping': ['id', 'entityType', 'oldId', 'newId', 'createdAt', 'updatedAt'],
    'PTW_MAP_COORDINATES': ['id', 'name', 'latitude', 'longitude', 'zoom', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'PTW_DEFAULT_COORDINATES': ['latitude', 'longitude', 'zoom', 'updatedAt', 'updatedBy'],
    'Training': ['id', 'name', 'trainer', 'trainingType', 'date', 'expiryDate', 'factory', 'factoryName', 'location', 'locationName', 'startTime', 'endTime', 'hours', 'startDate', 'participants', 'participantsCount', 'status', 'createdAt', 'updatedAt'],
    'TrainingAttendance': ['id', 'trainingId', 'date', 'expiryDate', 'trainingType', 'factory', 'factoryName', 'employeeCode', 'employeeName', 'position', 'department', 'topic', 'trainer', 'startTime', 'endTime', 'totalHours', 'createdAt', 'updatedAt'],
    'LegalTrainings': ['id', 'title', 'legalReference', 'legalArticle', 'category', 'frequency', 'targetGroup', 'department', 'factory', 'factoryName', 'scheduledDate', 'actualDate', 'trainer', 'trainerQualification', 'duration', 'participantsCount', 'status', 'expiryDate', 'nextDueDate', 'certificateRequired', 'complianceStatus', 'penaltyForNonCompliance', 'notes', 'attachments', 'createdBy', 'createdAt', 'updatedAt'],
    'LegalTrainingAttendees': ['id', 'legalTrainingId', 'legalTrainingTitle', 'employeeCode', 'employeeName', 'employeePosition', 'department', 'factory', 'factoryName', 'attendanceDate', 'attendanceStatus', 'score', 'certificateNumber', 'certificateDate', 'certificateExpiryDate', 'certificateImage', 'notes', 'createdBy', 'createdAt', 'updatedAt'],
    'LegalRegister': ['id', 'title', 'issuingAuthority', 'lawType', 'lawNumber', 'lawYear', 'issueDate', 'effectiveDate', 'category', 'legalReference', 'legalArticles', 'scopeOfApplication', 'responsibleDepartment', 'summary', 'status', 'priority', 'nextReviewDate', 'amendments', 'notes', 'createdBy', 'createdAt', 'updatedAt'],
    'ClinicVisits': [
        'id', 'personType', 'employeeCode', 'employeeNumber', 'employeeName', 'employeePosition', 'employeeDepartment',
        'factory', 'factoryName', 'employeeLocation', 'visitDate', 'exitDate', 'visitType', 'reason', 'diagnosis',
        'treatment', 'medicationsDispensed', 'medicationsDispensedQty', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'
    ],
    'ClinicContractorVisits': [
        'id', 'personType', 'contractorName', 'contractorWorkerName', 'contractorPosition', 'externalName',
        'factory', 'factoryName', 'workArea', 'visitDate', 'exitDate', 'visitType', 'reason', 'diagnosis',
        'treatment', 'medicationsDispensed', 'medicationsDispensedQty', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'
    ],
    'Medications': ['id', 'name', 'type', 'usage', 'purchaseDate', 'expiryDate', 'status', 'daysRemaining', 'quantityAdded', 'remainingQuantity', 'location', 'notes', 'createdBy', 'createdById', 'createdAt', 'updatedAt', 'updatedBy'],
    'SickLeave': ['id', 'personType', 'employeeCode', 'employeeNumber', 'employeeName', 'department', 'contractorName', 'externalName', 'startDate', 'endDate', 'daysCount', 'reason', 'medicalNotes', 'treatingDoctor', 'status', 'linkedRegistryId', 'createdBy', 'createdAt', 'updatedAt', 'updatedBy'],
    'Injuries': ['id', 'personType', 'employeeCode', 'employeeNumber', 'employeeName', 'employeePosition', 'employeeDepartment', 'department', 'factory', 'factoryName', 'subLocation', 'subLocationName', 'injuryDate', 'injuryType', 'injuryBodyPart', 'injuryLocation', 'injuryDescription', 'actionsTaken', 'treatment', 'status', 'attachments', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ClinicContractorInjuries': ['id', 'personType', 'contractorName', 'personName', 'contractorPosition', 'department', 'factory', 'factoryName', 'subLocation', 'subLocationName', 'injuryDate', 'injuryType', 'injuryBodyPart', 'injuryLocation', 'injuryDescription', 'actionsTaken', 'treatment', 'status', 'attachments', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ClinicInventory': ['id', 'medicationName', 'quantity', 'expiryDate', 'location', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ClinicStaff': ['id', 'userId', 'userEmail', 'userName', 'staffRole', 'jobTitle', 'department', 'isActive', 'sortOrder', 'createdAt', 'updatedAt'],
    'ClinicStaffAttendance': ['id', 'staffId', 'userId', 'userName', 'userEmail', 'staffRole', 'date', 'checkIn', 'checkOut', 'workDuration', 'status', 'sessionId', 'source', 'notes', 'createdAt', 'updatedAt'],
    'ClinicStaffTimeOffRequests': ['id', 'requestType', 'staffId', 'userId', 'userEmail', 'userName', 'staffRole', 'dateFrom', 'dateTo', 'timeFrom', 'timeTo', 'durationHours', 'durationDays', 'reason', 'status', 'reviewedById', 'reviewedByName', 'reviewNotes', 'requestedAt', 'reviewedAt', 'createdAt', 'updatedAt'],
    'ClinicStaffLeaveQuota': ['id', 'staffId', 'userId', 'userEmail', 'userName', 'periodType', 'periodKey', 'leaveDaysQuota', 'permissionCountQuota', 'notes', 'updatedById', 'updatedByName', 'createdAt', 'updatedAt'],
    'FireEquipment': ['id', 'equipmentNumber', 'equipmentType', 'location', 'checkDate', 'status', 'inspector', 'notes', 'createdAt', 'updatedAt'],
    'PPE': ['id', 'receiptNumber', 'employeeName', 'employeeCode', 'employeeNumber', 'employeeDepartment', 'employeePosition', 'employeeBranch', 'employeeLocation', 'equipmentType', 'quantity', 'receiptDate', 'status', 'createdAt', 'updatedAt'],
    'Violations': ['id', 'isoCode', 'personType', 'employeeId', 'employeeName', 'employeeCode', 'employeeNumber', 'employeePosition', 'employeeDepartment', 'contractorId', 'contractorName', 'contractorWorker', 'contractorPosition', 'contractorDepartment', 'violationTypeId', 'violationType', 'fineAmount', 'violationDate', 'violationTime', 'violationLocation', 'violationLocationId', 'violationPlace', 'violationPlaceId', 'violationDetails', 'severity', 'actionTaken', 'status', 'photo', 'violationSequenceInMonth', 'createdAt', 'updatedAt'],
    'Blacklist_Register': ['id', 'serialNumber', 'factory', 'factoryId', 'location', 'locationId', 'fullName', 'idNumber', 'photo', 'job', 'department', 'banReason', 'banDate', 'bannedBy', 'editor', 'notes', 'createdAt', 'updatedAt'],
    'Contractors': ['id', 'name', 'serviceType', 'contractNumber', 'startDate', 'endDate', 'status', 'contactPerson', 'phone', 'email', 'createdAt', 'updatedAt'],
    'Employees': ['employeeNumber', 'name', 'department', 'job', 'nationalId', 'birthDate', 'age', 'hireDate', 'gender', 'phone', 'insuranceNumber', 'sapId', 'branch', 'location', 'position', 'email', 'photo', 'createdAt', 'updatedAt', 'id', 'status', 'resignationDate'],
    'BehaviorMonitoring': ['id', 'isoCode', 'employeeId', 'employeeCode', 'employeeNumber', 'employeeName', 'department', 'job', 'factory', 'factoryId', 'factoryName', 'subLocation', 'subLocationId', 'subLocationName', 'behaviorType', 'date', 'rating', 'correctiveAction', 'correctiveActionDetails', 'description', 'photo', 'createdAt', 'updatedAt'],
    'ContractorBehaviorMonitoring': ['id', 'isoCode', 'contractorId', 'contractorName', 'contractorWorker', 'department', 'job', 'factory', 'factoryId', 'factoryName', 'subLocation', 'subLocationId', 'subLocationName', 'behaviorType', 'date', 'rating', 'correctiveAction', 'correctiveActionDetails', 'description', 'photo', 'createdAt', 'updatedAt'],
    'ChemicalSafety': ['id', 'isoCode', 'chemicalName', 'trainer', 'date', 'status', 'description', 'createdAt', 'updatedAt'],
    'Chemical_Register': ['id', 'serialNumber', 'rmName', 'physicalShape', 'purposeOfUse', 'methodOfApplication', 'department', 'msdsArabic', 'msdsEnglish', 'localImport', 'manufacturer', 'agentEgypt', 'containerType', 'containerDisposalMethod', 'hazardClass', 'hazardDescription', 'locationStore', 'qtyYear', 'nfpaDiamond', 'createdAt', 'updatedAt'],
    'DailyObservations': ['id', 'isoCode', 'siteId', 'siteName', 'placeId', 'locationName', 'observationType', 'subCategory', 'date', 'shift', 'details', 'correctiveAction', 'responsibleDepartment', 'riskLevel', 'observerName', 'expectedCompletionDate', 'status', 'gpsCoordinates', 'gpsAccuracy', 'mapsUrl', 'overdays', 'timestamp', 'reviewedBy', 'remarks', 'attachments', 'createdAt', 'updatedAt', 'workflowStage', 'submittedBy', 'submittedByEmail', 'submittedAt', 'specialistReviewedBy', 'specialistReviewedAt', 'specialistComments', 'managerApprovedBy', 'managerApprovedAt', 'managerComments', 'departmentActionBy', 'departmentActionAt', 'rejectionReason', 'dueReminderSentAt', 'assignedToName', 'assignedToEmail', 'comments', 'updates', 'timeLog'],
    'DailySafetyCheckList': ['id', 'reportNumber', 'siteId', 'siteName', 'date', 'inspectorName', 'shift', 'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11', 'q12', 'q13', 'q14', 'q15', 'q15Reading', 'q16', 'q17', 'notes', 'formSubmittedAt', 'createdAt', 'updatedAt'],
    'ISODocuments': ['id', 'isoCode', 'name', 'type', 'version', 'department', 'createdAt', 'updatedAt'],
    'ISOProcedures': ['id', 'isoCode', 'name', 'department', 'version', 'createdAt', 'updatedAt'],
    'ISOForms': ['id', 'isoCode', 'name', 'type', 'createdAt', 'updatedAt'],
    'DocumentCodes': ['id', 'code', 'documentName', 'documentType', 'department', 'status', 'description', 'createdAt', 'updatedAt', 'createdBy'],
    'DocumentVersions': ['id', 'documentCodeId', 'documentCode', 'versionNumber', 'issueDate', 'revisionDate', 'status', 'notes', 'isActive', 'createdAt', 'updatedAt', 'createdBy'],
    'SOPJHA': ['id', 'isoCode', 'type', 'title', 'department', 'issueDate', 'status', 'version', 'procedures', 'hazards', 'requiredPPE', 'createdAt', 'updatedAt'],
    'RiskAssessments': ['id', 'isoCode', 'activity', 'location', 'date', 'status', 'riskLevel', 'correctiveActions', 'createdAt', 'updatedAt'],
    'LegalDocuments': ['id', 'isoCode', 'documentName', 'documentType', 'documentNumber', 'issuedBy', 'issueDate', 'expiryDate', 'alertDays', 'status', 'description', 'documentLink', 'documentImage', 'createdAt', 'updatedAt'],
    'HSEAudits': ['id', 'type', 'date', 'auditor', 'status', 'description', 'createdAt', 'updatedAt'],
    'HSENonConformities': ['id', 'date', 'description', 'status', 'createdAt', 'updatedAt'],
    'HSECorrectiveActions': ['id', 'description', 'responsible', 'dueDate', 'status', 'createdAt', 'updatedAt'],
    'HSEObjectives': ['id', 'name', 'description', 'dueDate', 'responsible', 'status', 'createdAt', 'updatedAt'],
    'HSERiskAssessments': ['id', 'activity', 'location', 'date', 'riskLevel', 'status', 'createdAt', 'updatedAt'],
    'EnvironmentalAspects': ['id', 'name', 'description', 'impact', 'createdAt', 'updatedAt'],
    'EnvironmentalMonitoring': ['id', 'aspect', 'date', 'value', 'unit', 'status', 'createdAt', 'updatedAt'],
    'Sustainability': ['id', 'name', 'description', 'startDate', 'status', 'createdAt', 'updatedAt'],
    'CarbonFootprint': ['id', 'date', 'source', 'co2Equivalent', 'description', 'createdAt', 'updatedAt'],
    'WasteManagement': ['id', 'date', 'wasteType', 'quantity', 'disposalMethod', 'createdAt', 'updatedAt'],
    'WasteManagement_RegularWasteTypes': ['id', 'name', 'createdAt', 'updatedAt'],
    'WasteManagement_RegularWasteRecords': ['id', 'serialNumber', 'date', 'location', 'wasteType', 'quantity', 'unit', 'department', 'storageMethod', 'notes', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'WasteManagement_RegularWasteSales': ['id', 'transactionNumber', 'date', 'location', 'wasteType', 'quantity', 'unit', 'unitPrice', 'totalValue', 'buyerName', 'paymentMethod', 'notes', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'WasteManagement_HazardousWasteRecords': ['id', 'serialNumber', 'date', 'location', 'wasteType', 'quantity', 'unit', 'hazardClassification', 'storageMethod', 'transportCompany', 'treatmentFacility', 'transportDate', 'documents', 'notes', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'WaterManagement_Records': ['id', 'serialNumber', 'date', 'monthYear', 'location', 'source', 'startReading', 'endReading', 'totalConsumption', 'unit', 'department', 'notes', 'hasAlert', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'GasManagement_Records': ['id', 'serialNumber', 'date', 'monthYear', 'location', 'source', 'startReading', 'endReading', 'totalConsumption', 'unit', 'department', 'notes', 'hasAlert', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ElectricityManagement_Records': ['id', 'serialNumber', 'date', 'monthYear', 'location', 'source', 'startReading', 'endReading', 'totalConsumption', 'unit', 'department', 'notes', 'hasAlert', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'EnergyEfficiency': ['id', 'date', 'department', 'energyConsumption', 'efficiencyPercentage', 'notes', 'createdAt', 'updatedAt'],
    'WaterManagement': ['id', 'date', 'usageType', 'quantity', 'waterSource', 'createdAt', 'updatedAt'],
    'RecyclingPrograms': ['id', 'programName', 'materialType', 'recyclingRate', 'status', 'description', 'createdAt', 'updatedAt'],
    'PeriodicInspections': ['id', 'inspectionType', 'location', 'date', 'inspector', 'status', 'findings', 'recommendations', 'createdAt', 'updatedAt'],
    'SafetyBudget': ['id', 'category', 'description', 'amount', 'date', 'status', 'approvedBy', 'createdAt', 'updatedAt'],
    'SafetyPerformanceKPIs': ['id', 'recordType', 'year', 'month', 'kpiName', 'target', 'actual', 'date', 'status', 'notes', 'hoursWorked', 'neboshStatus', 'createdAt', 'updatedAt', 'updatedBy'],
    'KPIAnnualPlans': ['id', 'year', 'indicatorType', 'objective', 'kpi', 'target', 'goal', 'improvementPlan', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec', 'total', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'HSEMonitoringPlans': ['id', 'year', 'frequency', 'activity', 'activityDescription', 'area', 'responsibility', 'recordDocument', 'target_jan', 'target_feb', 'target_mar', 'target_apr', 'target_may', 'target_jun', 'target_jul', 'target_aug', 'target_sep', 'target_oct', 'target_nov', 'target_dec', 'executed_jan', 'executed_feb', 'executed_mar', 'executed_apr', 'executed_may', 'executed_jun', 'executed_jul', 'executed_aug', 'executed_sep', 'executed_oct', 'executed_nov', 'executed_dec', 'total_target', 'total_executed', 'score', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ActionTrackingRegister': ['id', 'serialNumber', 'issueDate', 'typeOfIssue', 'observationClassification', 'observationIssueHazard', 'correctivePreventiveAction', 'rootCause', 'department', 'location', 'riskRating', 'responsible', 'originalTargetDate', 'status', 'observerName', 'shift', 'sourceModule', 'sourceId', 'sourceData', 'timeLog', 'updates', 'comments', 'closedAt', 'closedBy', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ActionTrackingSettings': ['id', 'typeOfIssueList', 'classificationList', 'rootCauseList', 'typeClassificationMapping', 'classificationRootCauseMapping', 'statusList', 'riskRatingList', 'departmentList', 'locationList', 'responsibleList', 'shiftList', 'permissions', 'updatedAt'],
    'Budget': ['id', 'category', 'description', 'amount', 'date', 'status', 'createdAt', 'updatedAt'],
    'KPIs': ['id', 'name', 'target', 'actual', 'date', 'status', 'createdAt', 'updatedAt'],
    'EmergencyAlerts': ['id', 'title', 'message', 'type', 'priority', 'status', 'targetAudience', 'channels', 'scheduledDate', 'sentDate', 'createdBy', 'createdAt', 'updatedAt'],
    'EmergencyPlans': ['id', 'name', 'type', 'description', 'procedures', 'responsibleTeam', 'equipment', 'contacts', 'status', 'lastReview', 'nextReview', 'createdAt', 'updatedAt'],
    'EmergencyPlansUpdates': ['id', 'sectionKey', 'sectionNameAr', 'sectionNameEn', 'titleAr', 'titleEn', 'subtitleAr', 'subtitleEn', 'imageUrl', 'contentHtmlAr', 'contentHtmlEn', 'order', 'isActive', 'siteId', 'lastUpdatedBy', 'lastUpdatedAt', 'createdAt', 'updatedAt'],
    'EmployeeTrainingMatrix': ['id', 'employeeId', 'employeeCode', 'employeeName', 'position', 'department', 'topics', 'trainingRecords', 'lastUpdated', 'createdAt', 'updatedAt'],
    'ContractorTrainings': ['id', 'contractorId', 'contractorName', 'trainingName', 'trainer', 'date', 'participants', 'topics', 'topic', 'traineesCount', 'startTime', 'endTime', 'durationMinutes', 'totalHours', 'location', 'locationId', 'subLocation', 'subLocationId', 'notes', 'status', 'createdAt', 'updatedAt'],
    'ExternalWorkforceMonthly': ['id', 'year', 'contractorId', 'contractorCode', 'contractorName', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec', 'total', 'createdAt', 'updatedAt', 'updatedBy'],
    'PeriodicInspectionCategories': ['id', 'name', 'description', 'frequency', 'isDefault', 'createdAt', 'updatedAt'],
    'PeriodicInspectionChecklists': ['id', 'categoryId', 'categoryName', 'items', 'createdAt', 'updatedAt'],
    'PeriodicInspectionSchedules': ['id', 'categoryId', 'categoryName', 'location', 'scheduledDate', 'status', 'assignedTo', 'frequency', 'createdAt', 'updatedAt'],
    'PeriodicInspectionRecords': ['id', 'scheduleId', 'categoryId', 'categoryName', 'location', 'inspectionDate', 'inspector', 'result', 'findings', 'recommendations', 'status', 'createdAt', 'updatedAt'],
    'PeriodicEquipmentTypes': ['id', 'name', 'icon', 'linkedTemplateId', 'description', 'isDefault', 'active', 'order', 'createdAt', 'updatedAt'],
    'PeriodicEquipmentAssets': ['id', 'assetNumber', 'typeId', 'typeName', 'location', 'subLocation', 'factory', 'factoryId', 'manufacturer', 'model', 'serialNumber', 'manufacturingYear', 'installationDate', 'status', 'responsible', 'notes', 'qrCodeData', 'lastInspection', 'nextInspection', 'createdAt', 'updatedAt'],
    'PeriodicEquipmentInspections': ['id', 'assetId', 'assetNumber', 'inspectionDate', 'inspector', 'result', 'checklistResults', 'findings', 'status', 'createdAt', 'updatedAt'],
    'FireEquipmentAssets': ['id', 'factory', 'factoryId', 'location', 'subLocation', 'subLocationId', 'type', 'capacity', 'capacityKg', 'siteNumber', 'number', 'manufacturer', 'manufacturingYear', 'productionDate', 'serialNumber', 'status', 'installationMethod', 'model', 'installationDate', 'lastServiceDate', 'responsible', 'notes', 'qrCodeData', 'assetNumber', 'equipmentType', 'lastInspection', 'nextInspection', 'createdAt', 'updatedAt'],
    'FireEquipmentInspections': ['id', 'assetId', 'assetNumber', 'inspectionDate', 'inspector', 'result', 'findings', 'actions', 'status', 'createdAt', 'updatedAt'],
    'ViolationTypes': ['id', 'name', 'description', 'fineAmount', 'severity', 'category', 'defaultAction', 'isActive', 'createdAt', 'updatedAt'],
    'SafetyBudgets': ['id', 'year', 'budgetAmount', 'allocatedAmount', 'spentAmount', 'remainingAmount', 'status', 'createdAt', 'updatedAt'],
    'SafetyBudgetTransactions': ['id', 'budgetId', 'category', 'description', 'amount', 'type', 'date', 'approvedBy', 'status', 'createdAt', 'updatedAt'],
    'SafetyBudgetPurchaseOrders': ['id', 'prNo', 'prDate', 'itemCodeNo', 'itemsDescription', 'detailsRemarks', 'quantity', 'prStatus', 'poNo', 'poStatus', 'note', 'createdAt', 'updatedAt', 'updatedBy'],
    'PPEMatrix': ['id', 'employeeId', 'employeeCode', 'employeeName', 'position', 'department', 'ppeItems', 'lastUpdated', 'createdAt', 'updatedAt'],
    'PPE_Stock': ['itemId', 'itemCode', 'itemName', 'category', 'stock_IN', 'stock_OUT', 'balance', 'minThreshold', 'supplier', 'lastUpdate', 'createdAt', 'updatedAt'],
    'PPE_Transactions': ['id', 'itemId', 'date', 'action', 'quantity', 'issuedTo', 'remarks', 'createdAt', 'updatedAt'],
    'ApprovedContractors': ['id', 'code', 'isoCode', 'companyName', 'entityType', 'serviceType', 'licenseNumber', 'contractorId', 'approvalDate', 'expiryDate', 'status', 'notes', 'safetyReviewer', 'approvedBy', 'isActive', 'createdAt', 'updatedAt'],
    'ContractorEvaluations': ['id', 'contractorId', 'contractorName', 'evaluationDate', 'evaluatorName', 'projectName', 'location', 'generalNotes', 'items', 'compliantCount', 'totalItems', 'finalScore', 'finalRating', 'isoCode', 'status', 'approvedAt', 'approvedBy', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'ContractorApprovalRequests': [
        'id', 'requestType', 'companyName', 'serviceType', 'licenseNumber',
        'createdByName', 'approvedByName', 'contactPerson', 'phone', 'email',
        'notes', 'attachments', 'customFields', 'status', 'approvedAt', 'approvedBy',
        'createdAt', 'createdBy', 'updatedAt', 'contractorId', 'contractorName', 'evaluationData',
        'rejectedAt', 'rejectedBy', 'rejectedByName', 'rejectionReason', 'contractorData'
    ],
    'ContractorEvaluationApprovalRequests': [
        'id', 'contractorId', 'contractorName', 'evaluationData', 'status', 'createdBy', 'createdByName',
        'createdAt', 'approvedAt', 'approvedBy', 'approvedByName', 'rejectedAt', 'rejectedBy',
        'rejectedByName', 'rejectionReason', 'updatedAt', 'updatedBy', 'updatedByName', 'legacySource'
    ],
    'ContractorDeletionRequests': ['id', 'requestType', 'entityId', 'reason', 'status', 'createdBy', 'createdAt', 'updatedAt', 'approvedAt', 'approvedBy', 'approvedByName', 'rejectedAt', 'rejectedBy', 'rejectedByName', 'rejectionReason'],
    'ViolationApprovalRequests': [
        'id', 'requestType', 'violationData', 'originalViolationId', 'status', 'approvers', 'currentApproverIndex',
        'createdBy', 'createdByName', 'createdAt', 'approvedBy', 'approvedByName', 'approvedAt',
        'rejectedBy', 'rejectedByName', 'rejectedAt', 'rejectionReason', 'finalViolationId', 'notes', 'updatedAt', 'updatedBy'
    ],
    'ViolationApprovalSettings': ['id', 'requireApproval', 'defaultApprovers', 'bypassRoles', 'updatedBy', 'updatedByName', 'updatedAt', 'createdAt'],
    'ChangeRequests': ['id', 'requestNumber', 'title', 'description', 'changeType', 'priority', 'impact', 'status', 'requestedBy', 'requestedByEmail', 'requestedAt', 'factoryId', 'factoryName', 'subLocationId', 'subLocationName', 'dueDate', 'relatedModule', 'relatedProcess', 'riskAssessment', 'mitigationActions', 'fromDepartment', 'toDepartment', 'locationOther', 'technicalChangeSubType', 'changeContinuity', 'temporaryUntilDate', 'priorityUrgentReason', 'attachedDocumentsText', 'requestingDepartment', 'otherDepartments', 'affectedDepartments', 'documentsToAmendJson', 'committeeMembersJson', 'committeeRecommendations', 'employeeName', 'employeeCode', 'currentTasksDescription', 'newTasksDescription', 'administrativeChangeSubType', 'responsibleRequestingDepartment', 'responsibleImplementingDepartment', 'previousInjury', 'chronicDiseases', 'healthNotes', 'trainingRequirementsJson', 'reviewerName', 'reviewerNotes', 'approvedBy', 'approvedAt', 'rejectedBy', 'rejectedAt', 'rejectionReason', 'implementedAt', 'implementedBy', 'closedAt', 'closedBy', 'approvalFlowJson', 'currentApprovalStep', 'approvalStatus', 'timeLog', 'attachments', 'createdBy', 'createdAt', 'updatedAt', 'updatedBy'],
    'AuditLog': ['id', 'userId', 'userName', 'action', 'module', 'details', 'ipAddress', 'timestamp', 'createdAt', 'updatedAt'],
    'UserActivityLog': ['id', 'userId', 'username', 'userEmail', 'actionType', 'module', 'recordId', 'details', 'sessionId', 'sessionLoginTime', 'ipAddress', 'timestamp', 'createdAt', 'updatedAt'],
    'ClientErrorLog': ['id', 'level', 'message', 'stack', 'source', 'line', 'col', 'module', 'action', 'pageUrl', 'userAgent', 'appVersion', 'userId', 'userEmail', 'username', 'sessionId', 'fingerprint', 'status', 'extra', 'createdAt', 'updatedAt'],
    'AIAssistantSettings': ['id', 'userId', 'settings', 'preferences', 'createdAt', 'updatedAt'],
    'UserAILog': ['id', 'userId', 'userName', 'query', 'response', 'timestamp', 'createdAt', 'updatedAt'],
    'ObservationSites': ['id', 'name', 'location', 'description', 'status', 'createdAt', 'updatedAt'],
    'AnnualTrainingPlans': ['id', 'year', 'plans', 'status', 'createdAt', 'updatedAt'],
    'SafetyTeamMembers': ['id', 'name', 'jobTitle', 'department', 'contactInfo', 'email', 'phone', 'appointmentDate', 'positionLevel', 'photo', 'employeeCode', 'employeeNumber', 'status', 'createdAt', 'updatedAt'],
    'SafetyOrganizationalStructure': ['id', 'position', 'positionLevel', 'memberId', 'memberName', 'parentPositionId', 'order', 'description', 'createdAt', 'updatedAt'],
    'SafetyJobDescriptions': ['id', 'memberId', 'employeeId', 'jobTitle', 'roleDescription', 'responsibilities', 'tasks', 'workScope', 'requiredQualifications', 'createdAt', 'updatedAt'],
    'SafetyTeamKPIs': ['id', 'memberId', 'period', 'inspectionsCount', 'closedActionsCount', 'observationsCount', 'trainingsCount', 'incidentsHandledCount', 'nearMissCount', 'ptwCount', 'commitmentRate', 'targetInspections', 'targetActionsClosure', 'targetObservations', 'targetTrainings', 'targetCommitment', 'customKPIs', 'isManual', 'calculatedAt', 'createdAt', 'updatedAt'],
    'SafetyTeamTasks': ['id', 'memberId', 'taskTitle', 'taskDescription', 'taskType', 'priority', 'dueDate', 'status', 'assignedBy', 'completedDate', 'notes', 'createdAt', 'updatedAt'],
    'SafetyTeamPerformanceReports': ['id', 'memberId', 'period', 'startDate', 'endDate', 'reportData', 'summary', 'generatedAt', 'createdAt'],
    'SafetyTeamAttendance': ['id', 'memberId', 'date', 'checkIn', 'checkOut', 'workDuration', 'status', 'notes', 'createdAt', 'updatedAt'],
    'SafetyTeamLeaves': ['id', 'memberId', 'leaveType', 'startDate', 'endDate', 'daysCount', 'reason', 'approvalStatus', 'approvedBy', 'notes', 'createdAt', 'updatedAt'],
    'SafetyHealthManagementSettings': ['id', 'leaveTypes', 'attendanceStatuses', 'kpiTargets', 'organizationalStructureSettings', 'createdAt', 'updatedAt'],
    'Form_Settings_DB': ['id', 'sites', 'departments', 'safetyTeam', 'updatedAt', 'updatedBy'],
    'Violation_Types_DB': ['id', 'violationTypes', 'updatedAt', 'updatedBy'],
    'Form_Sites': ['id', 'name', 'description', 'isActive', 'sortOrder', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'Form_Places': ['id', 'siteId', 'siteName', 'name', 'description', 'isActive', 'sortOrder', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'Form_Departments': ['id', 'name', 'description', 'isActive', 'sortOrder', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'Form_SafetyTeam': ['id', 'name', 'position', 'phone', 'email', 'isActive', 'sortOrder', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'],
    'UserTasks': ['id', 'title', 'taskTitle', 'description', 'taskDescription', 'assignedTo', 'assignedDepartments', 'status', 'priority', 'dueDate', 'completionRate', 'userProgress', 'completedDate', 'createdBy', 'createdAt', 'updatedAt'],
    'SafetyCalendarCustomEvents': ['id', 'title', 'description', 'startDate', 'endDate', 'recurring', 'color', 'enabled', 'createdBy', 'createdAt', 'updatedAt'],
    'UserInstructions': ['id', 'type', 'title', 'description', 'content', 'assignedTo', 'assignedDepartments', 'isRead', 'readAt', 'createdBy', 'createdAt', 'updatedAt'],
    'ModuleManagement': ['id', 'moduleId', 'enabled', 'version', 'lastUpdated', 'updatedBy', 'updatedByName', 'notes', 'createdAt'],
    'Notifications': ['id', 'userId', 'type', 'priority', 'title', 'message', 'read', 'readAt', 'relatedId', 'relatedType', 'taskId', 'actionId', 'ptwId', 'scheduleId', 'trainingId', 'dueDate', 'scheduledDate', 'startDate', 'endDate', 'createdAt', 'updatedAt'],
    'BackupLog': ['id', 'backupType', 'backupName', 'fileId', 'fileUrl', 'fileName', 'fileSize', 'fileSizeFormatted', 'sheetsCount', 'totalRecords', 'sheetsDetails', 'sourceSpreadsheetId', 'sourceSpreadsheetName', 'status', 'duration', 'errorMessage', 'restoredFromBackupId', 'restoredSheets', 'errors', 'createdBy', 'createdById', 'createdAt', 'updatedAt'],
    'BackupSettings': ['id', 'autoBackupEnabled', 'backupTimes', 'maxBackupFiles', 'backupFolderName', 'retentionDays', 'notifyOnBackup', 'notifyOnFailure', 'updatedAt', 'updatedBy', 'updatedById'],
    'AppEmergencyNumbers': ['id', 'label', 'phone', 'sortOrder', 'isActive', 'createdAt', 'updatedAt'],
    'EmergencyFloorPlans': ['id', 'name', 'floor', 'factory', 'factoryId', 'factoryName', 'subLocationId', 'subLocationName', 'imageDriveId', 'imageWidth', 'imageHeight', 'sortOrder', 'isActive', 'qrToken', 'qrAnchorX', 'qrAnchorY', 'geoNwLat', 'geoNwLng', 'geoSeLat', 'geoSeLng', 'drawStampsJson', 'createdAt', 'updatedAt'],
    'EmergencyMapItems': ['id', 'floorPlanId', 'itemType', 'label', 'x', 'y', 'width', 'height', 'rotation', 'strokeColor', 'fillColor', 'status', 'notes', 'createdAt', 'updatedAt'],
    'PTWIssuingAuthorities': [
        'id', 'personType', 'employeeCode', 'contractorCompanyName', 'name', 'departmentId', 'departmentName', 'jobTitle', 'approvalRole', 'factory', 'location', 'sublocation', 'email', 'phone', 'isActive',
        'contractorFlag', 'coldWork', 'loto', 'hotWork', 'workAtHeight', 'confinedSpace', 'excavation', 'contractorPTW', 'liftingPlan', 'sortOrder', 'notes', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'
    ],
    'PTWContractorIssuingAuthorities': [
        'id', 'personType', 'employeeCode', 'contractorCompanyName', 'name', 'departmentId', 'departmentName', 'jobTitle', 'approvalRole', 'factory', 'location', 'sublocation', 'email', 'phone', 'isActive',
        'contractorFlag', 'coldWork', 'loto', 'hotWork', 'workAtHeight', 'confinedSpace', 'excavation', 'contractorPTW', 'liftingPlan', 'sortOrder', 'notes', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy'
    ],
    'SecurityOfficers': ['id', 'name', 'role', 'site', 'phone', 'isActive', 'createdAt', 'updatedAt'],
    'GateVisitors': [
        'Record ID', 'Entry Date', 'Entry Time', 'Visitor Name', 'Organization / Company',
        'National ID / Passport', 'Phone Number', 'Vehicle Plate', 'Target Site',
        'Target Hall / Area', 'Host Person & Dept', 'Visit Purpose', 'Badge #',
        'Security Officer / Registered By', 'Status', 'Exit Time', 'Duration (Minutes)', 'Signature URL', 'Created At Timestamp'
    ]
};

function getDefaultHeaders(sheetName) {
    return headersMap[sheetName] || [];
}

module.exports = {
    headersMap,
    getDefaultHeaders
};
